apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ephemeral
spec:
  description: Project for ephemeral access controller tests
  destinations:
  - namespace: ephemeral
    server: '*'
  roles:
  - description: admin
    name: admin
    policies:
    - p, proj:ephemeral:admin, applications, sync, ephemeral/ephemeral, allow
    - p, proj:ephemeral:admin, applications, action/*, ephemeral/ephemeral, allow
    - p, proj:ephemeral:admin, applications, delete/*/Pod/*, ephemeral/ephemeral, allow
    - p, proj:ephemeral:admin, logs, get, ephemeral/ephemeral/ephemeral, deny
  sourceRepos:
  - '*'
