apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
stringData:
  # leoluz password is "12345678" < this is just used for local tests!!! :P
  accounts.leoluz.passwordMtime: MjAyNC0wOC0wOFQwMDozMzozMFo=
  accounts.leoluz.tokens: W3siaWQiOiI4YWQ3MWQ3YS1kNmU1LTRhZTQtOGY1Mi05MThmZjZlNjJiZjUiLCJpYXQiOjE3MjMwNjM3OTF9LHsiaWQiOiI1Y2QwZjk0OS1lZmM1LTQ1ZmMtOTMzMC0zMjkwNDM2YjE3YTMiLCJpYXQiOjE3MjMwNjQwMTV9LHsiaWQiOiI4Y2NlNzY2Mi1hODExLTQzNmEtODJmZC1mMjFjMTk2MTA4NjAiLCJpYXQiOjE3MjMwNjQxMzR9XQ==
type: Opaque
