apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: metrics-demo
  labels:
    app: metrics-demo
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: metrics-demo
  strategy:
    canary:
      analysis:
        args:
          - name: ingress
            value: canary-demo
          # pod template hash from the latest ReplicaSet
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
        # Template options: error-rate-anomaly, latency-anomaly, unified-anomaly
        templates:
          - templateName: unified-anomaly
        startingStep: 1 
      canaryService: rollout-demo-app-canary-service
      stableService: rollout-demo-app-stable-service
      steps:
      - setWeight: 40
      - pause: {}
      - setWeight: 60
      - pause:
          duration: 10
      - setWeight: 80
      - pause:
          duration: 10
  template:
    metadata:
      labels:
        app: metrics-demo
    spec:
      containers:
        - name: app
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VERSION
              value: "metrics4"
          image: quay.io/numaio/numalogic-demo:metrics4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: service
              protocol: TCP
            - containerPort: 8490
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-demo
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: metrics-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-demo-metrics
  labels:
    prometheus: "true"
spec:
  ports:
    - name: metrics
      port: 8490
      protocol: TCP
      targetPort: 8490
  selector:
    app: metrics-demo
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-app-stable-service
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: metrics-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-demo-app-canary-service
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: metrics-demo
  type: NodePort
