apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            - url: http://metrics-server.argocd-metrics-server
