apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-kubecon

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.0-rc4/manifests/namespace-install.yaml
- clusterrolebinding-apiserver.yaml
- clusterrolebinding-app-controller.yaml

patchesStrategicMerge:
- metrics-extension-patch.yaml
- enable-proxy-ext.yaml
- rbac.yaml
- argocd-cm.yaml
