apiVersion: v1
kind: Service
metadata:
  name: multiple-protocol-port-svc
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  ports:
    - name: rtmpk
      port: 1986
      protocol: UDP
      targetPort: 1986
    - name: rtmp
      port: 1935
      targetPort: 1935
    - name: rtmpq
      port: 1935
      protocol: UDP
      targetPort: 1935
    - name: https
      port: 443
      targetPort: 443
    - name: http3
      port: 443
      protocol: UDP
      targetPort: 443
