apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sandbox-test-leoluz
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.intuit.com/nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - cat
            - non-existent-file
          initialDelaySeconds: 5
          periodSeconds: 180
