apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: httpbin

resources:
- required-labels-crd.yaml
- svc.yaml
- deployment.yaml
- mutation-add-label.yaml
- must-have-label.yaml
- cronjob.yaml
