apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: mutation-webhook
spec:
  match:
    scope: Namespaced
  location: "metadata.labels.devx-demo"
  parameters:
    assign:
      value: "FROM-MUTATION-WEBHOOK"
