apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-namespaces-services
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      prometheus: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
