apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cmp-sidecar
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    # repoURL: file:///Users/lalmeida1/dev/git/kube-tests
    repoURL: https://github.com/leoluz/kube-tests.git
    targetRevision: HEAD
    path: argocd/cmp-sidecar
    plugin:
      env:
        - name: some_var
          value: some_value

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: cmp-sidecar

  # Sync policy
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
