apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-demo
  namespace: argocd-kubecon
spec:
  project: default
  source:
    repoURL: https://github.com/leoluz/kube-tests.git
    targetRevision: HEAD
    path: argocd/metrics-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
