apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  name: server-side-diff-error
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: crossplane-test
  ignoreDifferences:
  - group: apps
    jqPathExpressions:
    - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
    - .spec.template.spec.initContainers[].env[].valueFrom.resourceFieldRef.divisor
    kind: Deployment
  project: default
  source:
    repoURL: file:///Users/lalmeida1/dev/git/kube-tests
    path: argocd/ssd-helm
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=false
