apiVersion: batch/v1
kind: CronJob
metadata:
  name: ssa-test
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            health-check: argocd
        spec:
          containers:
          - name: hi
            image: alpine:latest
            command: ["date"]
          restartPolicy: Never
